### ISSUE TITLE
*stein-regel

### ISSUE THREAD

**Issue by boyum** [draperunner/preposisjon#9]
Jeg la merke til at *stein-suffiksen mangler i `paaSuffix`-listen og ble nysgjerrig på om dette er et bevisst valg eller en uheldig utelatelse. Jeg vet ikke om det finnes noen regel på norsk for *stein-stedsnavn, men kommer på Utstein og Breistein som bruker preposisjonen "på". Utstein ligger allerede inne i `paaExceptions`, men [et kjapt og unøyaktig søk i GeoNorge sitt stedsnavns-API](https://ws.geonorge.no/stedsnavn/v1/navn?sok=%2Astein&fuzzy=false&utkoordsys=4258&treffPerSide=500&side=1
) gir over 1100 treff på `*stein`. (Første 499 her: https://gist.github.com/boyum/92c3842c4811ddb3aa12397305a91f3c)

Hvilken retning ønsker dere å ta?

**Comment by draperunner** [comment]
Høyrest ut som ein steinbra regel, spør du meg! Det å vere _i_ ein stein kan ikkje vere så vanleg, utanom Ulstein (kommune).
